version: '3'
services:
  group-sync:
    container_name: gitea-group-sync
    build: .
    image: ghcr.io/gitea-group-sync/gitea-group-sync
    environment:
      GITEA_TOKEN: c00c810bb668c63ce7cd8057411d2f560eac469c
      GITEA_URL: http://192.168.2.2:3000
      LDAP_URL: 192.168.2.2
      LDAP_TLS_PORT: 636
      BIND_DN: cn=admin,dc=planetexpress,dc=com
      BIND_PASSWORD: GoodNewsEveryone
      LDAP_FILTER: (&(objectClass=person)(memberOf=cn=%s,ou=people,dc=planetexpress,dc=com))
      LDAP_USER_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
      REP_TIME: '@every 1m'
